server:
  port: 8081

base:
  url:
    ga-product: http://localhost:8080/gatewayaggregator/product
    promotion: http://localhost:8080/gatewayaggregator/promotion
    review: http://localhost:8080/gatewayaggregator/reviews
    delta: http://localhost:8080/scattergather/delta
    frontier: http://localhost:8080/scattergather/frontier
    jet-blue: http://localhost:8080/scattergather/jetblue
    sop-product: http://localhost:8080/serviceorchestrator-parallel/product
    sop-user: http://localhost:8080/serviceorchestrator-parallel/user
    sop-inventory: http://localhost:8080/serviceorchestrator-parallel/inventory
    sop-shipping: http://localhost:8080/serviceorchestrator-parallel/shipping

