server:
  port: 8081

base:
  url:
    ga-product: http://localhost:8080/gatewayaggregator/product
    promotion: http://localhost:8080/gatewayaggregator/promotion
    review: http://localhost:8080/gatewayaggregator/reviews
    delta: http://localhost:8080/scattergather/delta
    frontier: http://localhost:8080/scattergather/frontier
    jet-blue: http://localhost:8080/scattergather/jetblue
    so-product: http://localhost:8080/serviceorchestrator/product

